### ISSUE TITLE
Windows Defender recognize as trojan

### ISSUE THREAD

**Issue by Cannasteve** [larscom/xbox360-controller-manager#1]
Hello i can't run the program or do an exception on the file via Windows Defender because Windows 10 Pro recognize it as a Trojan [http://hpics.li/ba0bb9e](url)

Can you help me please?

**Comment by larscom** [comment]
Hm strange, that does not happen to me. Ill take a look to it. In the meanwhile, you can exclude the file in windows defender.

**Comment by larscom** [comment]
Hi, this should be fixed in version 2.2

**Comment by Cannasteve** [comment]
Thank you very much
