### ISSUE TITLE
Xbox One Controller compatibility?

### ISSUE THREAD

**Issue by honza-pacuta** [larscom/xbox360-controller-manager#30]
Hello. Firstly thank you for this great utility.
Today I purchased a new Xbox One Controller - connected to PC via Bluetooth - and I was wondering whether your utility could support it as well?
Jan

**Comment by COWCATGames** [comment]
Personally I tested it quickly and it appears in the list with the battery level (most important info for me), but turning it off doesn't work.
So, partially supported I'd say.

**Comment by honza-pacuta** [comment]
I mainly use the functionality to "turn off", so I'd like that to work, if possible.

**Comment by larscom** [comment]
Hi, the problem is that i don't have such a controller..

Maybe someone else can make this and make a pull request.

**Comment by COWCATGames** [comment]
Hey larscom, thank you very much for this software! I've been looking for something like this for a decade!
I would if I could but I'm a game developer myself without much free time and not much knowledge of how hardware works.

**Comment by honza-pacuta** [comment]
And I'm a WPF/database/website developer also without experience on the hardware side.
@larscom Maybe if you could steer me into the direction where this is handled in your library, I could do some debugging.

**Comment by larscom** [comment]
@cyberangel 

see for example:
It checks if the 'guide' button is pressed and will turn off controller.

https://github.com/larscom/xbox360-controller-manager/blob/8b8dfd72dbb1908af0ed3b66f6e952bf1f5fd611/XBOX360_Controller/Gamepad/GamepadScanner.cs#L115

**Comment by honza-pacuta** [comment]
@larscom Thanks, this seems straightforward. I'll try it over the next few days.

**Comment by honza-pacuta** [comment]
@larscom So the problem is with the imported function from xinput1_3.dll
static extern int XInputPowerOffController(int playerIndex); which does nothing.

The controller is detected, everything works, the buttons pressed are identified correctly (Options+Start), but calling the imported function just returns without effect.

Note that I am using a bluetooth connected Xbox One controller. Maybe the xinput function only works with controllers connected using the wireless adapter? The more I'm thinking about it I suppose that's the difference. 🙂

**Comment by larscom** [comment]
Could be, i have only developed/tested this software with wireless xbox360 controllers connected via a wireless adapter. 
So unfortunately i can't help with other controllers :wink:
