### ISSUE TITLE
No longer functioning on Windows 10?

### ISSUE THREAD

**Issue by SimonSaid123** [larscom/xbox360-controller-manager#31]
Hello! I just came across this application and am very grateful that you have created it and made it available, but it doesn't seem to work for me. I have Xbox 360 controllers on an official Microsoft Xbox wireless receiver into my Intel NUC 8 i3 running the latest version of Windows 10. The applet runs, but regardless of if I use default or Guide button setting, it cannot seem to turn the controller off.

Any idea what I might be doing wrong? Or has Microsoft broken this application?

Thank you :)

**Comment by larscom** [comment]
Hi, is this still an issue? I have to test this out myself. Will come with an update soon

**Comment by SimonSaid123** [comment]
Hi Lars :) Thanks for responding. Yes, still happening on the latest build. Is there any system info or log that would be helpful?

**Comment by larscom** [comment]
Hi, i've just downloaded version 2.8 from github and it works on my machine. Windows 10 Professional latest build.

I am using a wireless xbox360 controller with an original xbox360 wireless receiver.

Do you get any error if you start the application?

**Comment by SimonSaid123** [comment]
Hi Lars! No, no errors, application looks like it's running properly, including systray icon and toast messages when they should be. Everything works except the actual switching off controller features. 🤔

**Comment by larscom** [comment]
I've tested: 

- start & back (it works, turns off controller)
-  the guide button (also works, but with settings changed in windows)

The guide button only works if you enable it in the menu AND if with these settings in windows (you need to keep xbox game bar ON, but disable the guide button for it)

![Untitled](https://user-images.githubusercontent.com/1215195/142759539-018e8dc0-7a8d-4943-ac64-2fa8337a4831.png)


turning it off with start & back works without changing anything in windows.

**Comment by SimonSaid123** [comment]
That fixed it! I had Game Bar switched off. Perhaps you could put something into the application that hints the user to do this.

Thank you so much for the fix and for providing this brilliant utility 🍻

**Comment by larscom** [comment]
No problem, glad that it worked out 😄

**Comment by D-Maxwell** [comment]
This should probably get added to the README.

**Comment by D-Maxwell** [comment]
Even with Game Bar switched on, neither the guide button nor clicking the controller entry in the context menu have any effect.

**Comment by Jottle** [comment]
Hi lars. This issue seems to be back in windows 10 again. Confirmed that I have all settings correct in your software and for the windows gamebar (when using guide button to shut down controller). Controller manager recognizes my wired 360 controller correctly, but none of the options will shut down the controller. Are you still supporting this software by any chance?
