### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by JoseArtunedo** [larscom/xbox360-controller-manager#32]
Its version of Xbox, in ESET antivirus it is detected by Malware, also after its execution it enables the download of Chrome Helper, an application that collects information and forwards it to certain servers. Tested on a virtual machine from scratch and performs the same

**Comment by larscom** [comment]
Some anti virus report this application as a virus, thats correct. But it's a false positive.

I don't know what you mean by collecting information and forwarding it to certain servers, this application doesn't collect any information. Do you have more information on that?
