### ISSUE TITLE
non-Xbox 360 controllers taking up slots in xbox 360 controller manager

### ISSUE THREAD

**Issue by bughaver** [larscom/xbox360-controller-manager#35]
Can non-Xbox 360 controllers be ignored? 

They are causing issues with the Xbox 360 controller manager where it is taking up one or more of the 4 slots and the Xbox 360 controllers will not interact with the manager. The controller manager won't give up the slot for the non-Xbox 360 controller until the app is restarted.

The current workaround is to turn on all the Xbox 360 controllers and then turn non-Xbox 360 controllers last.

**Comment by larscom** [comment]
hi, what kind of non-xbox360 controller do you have?

**Comment by bughaver** [comment]
Xbox series x

Regards,
Louis Saadeh

On 14 Jan 2023, at 01:27, Lars Kniep ***@***.***> wrote:

﻿

hi, what kind of non-xbox360 controller do you have?

**Comment by larscom** [comment]
Dont think its possible at the moment. Xbox series x is a GamePad, just like the xbox 360.

**Comment by bughaver** [comment]
Would it be possible to implement a checkbox against the connected controllers to control manager to disable them? Or filtering by controller name?

Regards,
Louis Saadeh

On 15 Jan 2023, at 08:47, Lars Kniep ***@***.***> wrote:

﻿

Dont think its possible at the moment. Xbox series x is a GamePad, just like the xbox 360.

**Comment by larscom** [comment]
Dont think so.

This is the API you can work with:
http://sharpdx.org/wiki/class-library-api/xinput/

Its an outdated library i use in this project, if there is any better alternative let me know.
